language: php
php:
- 5.4
- 5.3
env:
  global:
  - ZBOOTA_SERVER_AWS_REGION="us-east-1"
  - secure: PRa1/T4AVNHkxj8S7XH06oEbj31q5hGrWadfKikrieg6swoavEp8VjVSCH6VZ2NhXKOZoMcgoP19NHIgN3X1h+wQdOn0BImTP78+0cxGWsOHwAcHl9rvXiSo5rJKnCoGwSaIWEKXGg8deA4JPtVPMdrxWK2MUe4EoeR8TWPHl5bvelBr7LcJJZjYUycrzfxTZ9c4IORNEHBZADJsMeiozMYeCtCFYn96j4F2znhNlB9w/bSaC1Rim9s136jIy0ejm5hRw/s2tvLTISXpY2AJmMe+pWpZFEX3j0u0CNdZcEHAdA1jZT8b0oLnfDhcBXvj30qg8Osm9K0Je7G3dn+9weWSp5J79K0h2qDYC4OtrtJtqgnBupUnjKX9ujLMlEuFUkwcm4c6AeGBO+yYZbplJLzAkGj9oKxlVD1nQkjfqSHMCARMEAIxiiUAa8xnmlWdeVxgtKggj4PB0QTn0tKThwgL+ouIsAq1TfNZWR4K9zBJuWmQE/91uM6rNiilVrCRI5uELGSp040limm4cWSCENTgIYRFnaU5Jazn8LVEbKas/ugYxJG4vDUDAWajkMv2wPCY1J2MQiUGX1lyqpEn0Mut1m5g7XqWcL33/wzFYX6ahii4w5VUVqAaV3/26FXOX3MvFSSkDCIT3B16TAanhGo1cCDZPLSCWaXn/fyV20Q=
  - secure: PkI6WGOlszEF7+LhMjisvqgFyQQZkjveMuz+eBF+eIXH2zHpEm4PdHr8udDcU5xbCFeIKf87w2Ejpx92QTHMpd/73RnKST+e4k9oKgViVcxn2fLD9V/wsieHIZSiTqJNB5xVayo1mRkkRR32FtPJWONdxuWpXGIDEDQrqKjiOeYNzlB5yrz7AVnO34Gwd7cFuMuGMywPzBB1TfnJVUWHIu8os+9y4mz5sXrdKJoxOkyGffPlR3YitbRtK4eAf0xd5r1WTJ+7MGYm4nW//zPdNjwz5u1AhnHGbldq3hThvqdABn8mTZOuqBDyQYwk+xbsyqFAt5F5Tg8N4461omO9801711m6mykKRekbPNpmHHzzU2sPDOJLnWm0etrpMF/p5I6p4078pk5lUXvrLwvwxvqadK7zziwwGFM9lDEHLbTBDcHwuTs9qCqqO2cLS4NyXSa501uspu5dMxj8upkkAI6s7kAUR1BoGZOWwGXfu/CE6k15rcDKoWQuPkk3Hs+QNMj2wjLOSS9KinHU3NLFiMrbd+Ug0UTP91pWbmxB9QhyM4Ftxb89CQPGUVMmqNTGRU9pXDSJ0QW94e+NRCuoJ8Ol2D30dgabzZ4AGsEY/v03U0WchxXif7YcifqfKjbq3rDLiNYM/DXc4KwycpjqZlipFn1oaTW83WRdLpatJG4=
sudo: required
before_script:
- composer install
- bash scripts/env2conf.sh && bash scripts/env2conf.sh | sudo tee /etc/zboota-server-config.php > /dev/null
